### ISSUE TITLE
频繁报错

### ISSUE THREAD

**Issue by JLS706** [fanchenio/DawnLauncher#12]

**Comment by JLS706** [comment]
![2023-11-04_133259](https://github.com/fanchenio/DawnLauncher/assets/75190532/bcd123af-2a91-4890-91f7-469629708756)
频繁出现此tan'ch弹窗

**Comment by fanchenio** [comment]
这个问题正在排查，不影响正常使用，先忍一下。

**Comment by fanchenio** [comment]
已修复
