### ISSUE TITLE
能不能出个tarui版的，这个electron包太大了

### ISSUE THREAD

**Issue by 2926295173** [fanchenio/DawnLauncher#15]

**Comment by fanchenio** [comment]
tauri本身API就很少，我做过tauri版本的，发现好多功能都实现不了，没办法，比如从桌面拖动文件到Dawn里面，tauri就不能实现拖动的时候并改变css样式，electron就可以，剩下不支持的就太多太多了。

**Comment by 2926295173** [comment]
原来如此
