### ISSUE TITLE
部分应用图标偏小，在桌面显示正常

### ISSUE THREAD

**Issue by H1DDENADM1N** [fanchenio/DawnLauncher#18]
![PixPin_2023-12-04_17-32-07](https://github.com/fanchenio/DawnLauncher/assets/65646535/f43bcacf-94f8-4582-8b16-5def7422a3d0)

**Comment by fanchenio** [comment]
因为图标是先获取256大小的图标，然后根据像素点判断透明的区域，如果大于70%的话，就代表是一个小图标，然后会在获取48大小的图标，按道理来说，你这些图标应该透明区域都大于70%，应该会获取到小图标，我最近没时间，等我有时间我排查看一下。
