### ISSUE TITLE
那个 能够读取音速启动的配置文件吗

### ISSUE THREAD

**Issue by lhj5426** [fanchenio/DawnLauncher#20]
在被窝躺着刷B站偶然看到有UP介绍大佬开发的工具
然后 保存了网址今天下来看了下 
有个问题 
![image](https://github.com/fanchenio/DawnLauncher/assets/30548000/4ad1101f-2371-43c6-b7fe-aeffaeae14c9)
我发现不是念旧 而是 从一个软件转移到另外一个软件的  有时候成本太高 了
特别是 长时间的使用 成本就更高了 
所以 就想发个issues 问一下开发者大佬
能不能够支持从其他软件的备份文件导入到您开发的软里呢
比如音速启动6 的备份文件 这个软件我从201几年就开始用 用了 至少快10年了
是手动迁移这个 工具箱 里的 各种东西 着实 成本很高 如果能够支持从其他的软件里 导入其他软件的备份 那么就0成本迁移 哈哈 
有点异想天开了？

**Comment by fanchenio** [comment]
这个难度太大了，而且不是短时间能完成的。

**Comment by lhj5426** [comment]
> 这个难度太大了，而且不是短时间能完成的。

哈哈 回复的好快。。 确实呢    如果从0开始用的话确实是个不错的工具
