### ISSUE TITLE
一些文件名显示不正确的问题

### ISSUE THREAD

**Issue by FiendFEARing** [fanchenio/DawnLauncher#27]
1、这样多个点的目录文件名显示不正确
![image](https://github.com/fanchenio/DawnLauncher/assets/40036715/530c5d45-6279-41f9-b01f-cbe762808ac1)

2、如果只修改了大小写不会使这里的文件名刷新
![image](https://github.com/fanchenio/DawnLauncher/assets/40036715/dba53102-723a-4f2d-97c2-bca7a31fbb84)

**Comment by fanchenio** [comment]
下个版本会修复。

**Comment by fanchenio** [comment]
已修复。
