### ISSUE TITLE
长期使用这类用户的六点建议

### ISSUE THREAD

**Issue by insvl1129** [fanchenio/DawnLauncher#28]
版本: 1.3.6

1. **绝对路径**
设置里加入默认相对或者绝对路径选项
经使用, 发现相对路径无法使用, 项目失效了才能切换到相对路径

3. **字体建议** 
设置字体无法设置, 分类字体无法设置, 项目字体可以设置这非常棒

4. **版本升级**
便携式为exe应用程序, 打开后选择释放路径, 如果释放的目录检测到旧版本, 自动保留配置替换掉需要升级的文件即可

5. **主题**
目前体验很棒, 希望添加css样式支持

6. **盈利**
提供语言配置文件, 可自行添加语言, 针对人群范围增加.
效仿"FreeFileSync"软件, 免费版提供安装版, 捐献版提供便携式安装版, 帮助界面会有感谢捐献人信息等, 非常有仪式感.

其他:
体验下来非常棒, 但路径转换目前无效状态, 手动切换路径也没办法, 不然我就一个个迁移过来了.

**Comment by fanchenio** [comment]
1. 默认相对绝对，后续会增加，相对路径只有在跟Dawn Launcher一个盘下才会转换。
2. 字体后续会加。
3. 升级这个等有时间研究一下。
4. 自定义css有打算这么做。
5. 关于盈利，我后续是有打算出买断制的Pro版本。

谢谢支持，如果还有疑问，可以加QQ群。
