### ISSUE TITLE
程序无响应-打开程序变成Dawn Launcher子进程

### ISSUE THREAD

**Issue by onegitting** [fanchenio/DawnLauncher#29]
![image](https://github.com/fanchenio/DawnLauncher/assets/132970523/9cd314ed-5104-4c64-98bc-7618a0e5ec5d)
偶尔会出现以下情况，打开的软件作为DawnLauncher的子进程存在，导致DawnLauncher无法打开新的软件，必须结束程序后，重新打开DawnLauncher，然后再次打开的程序不会作为子程序存在，出现问题的系统版本 Windows 11 专业版23H2

**Comment by fanchenio** [comment]
好的，我排查一下。

**Comment by fanchenio** [comment]
使用最新版本试试。

**Comment by fanchenio** [comment]
> > 使用最新版本试试。
> 
> 不懂就问，出os了没

等2077年。
