### ISSUE TITLE
1.3.6版本，资源管理器菜单无法打开

### ISSUE THREAD

**Issue by onegitting** [fanchenio/DawnLauncher#30]
![image](https://github.com/fanchenio/DawnLauncher/assets/132970523/37e60f9e-44c1-4971-b3d5-7cc4e42960cb)
![Snipaste_2024-01-17_15-40-56](https://github.com/fanchenio/DawnLauncher/assets/132970523/8b62d908-dcd7-4083-ba95-afc558515a5e)

**Comment by fanchenio** [comment]
去官网下载最新版本。
