### ISSUE TITLE
子分类间拖动存在问题

### ISSUE THREAD

**Issue by xuanyue1024** [fanchenio/DawnLauncher#34]
![yhc_2024-02-04_2151-07](https://github.com/fanchenio/DawnLauncher/assets/99373612/01e475e0-aebd-4c4e-b9cd-fb2c86b87719)
该拖动的成功了，不该拖动的拖到其它子分类了，具体看图😢

**Comment by xuanyue1024** [comment]
目前解决办法只能是先移动到其它分类，再放回来

**Comment by fanchenio** [comment]
收到。

**Comment by fanchenio** [comment]
我这面试了好多遍都没有复现，有什么具体步骤吗？

**Comment by xuanyue1024** [comment]
> 我这面试了好多遍都没有复现，有什么具体步骤吗？

不清楚，就直接这样有问题了，过程都在gif图中
