### ISSUE TITLE
打开项目失败

### ISSUE THREAD

**Issue by onegitting** [fanchenio/DawnLauncher#36]
开机运行一段时间后，所有项目单击无法打开，但其他右键菜单都可以运行，重启系统后报错如下述图片。
DawnLauncher 版本：1.3.6
windows 版本：Windows 11 专业版 23H2 22631.3155
![微信图片_20240226165244](https://github.com/fanchenio/DawnLauncher/assets/132970523/dd1e790c-390d-4146-ac7e-8bc1f8366e96)

**Comment by fanchenio** [comment]
下载最新版本试试。
