### ISSUE TITLE
【bug】高分辨率导出数据后，恢复到低分辨率窗口无法移动

### ISSUE THREAD

**Issue by wjx0912** [fanchenio/DawnLauncher#38]
从2560x1440电脑导出数据（dawn窗口可能800*1000），恢复到低分辨率电脑（1440x900），标题栏被现实到最外面了，程序无法移动，也无法resize

**Comment by fanchenio** [comment]
如果只导出data数据的话，不会包含窗口尺寸信息，窗口尺寸都存在缓存文件里，不会导出，是不是其他情况导致的呢？请截个图我看看。

**Comment by fanchenio** [comment]
> ![image](https://private-user-images.githubusercontent.com/5556482/313034690-45e68c6e-179f-4f54-a035-5eb0470ae902.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MDA3NjMsIm5iZiI6MTcxMDUwMDQ2MywicGF0aCI6Ii81NTU2NDgyLzMxMzAzNDY5MC00NWU2OGM2ZS0xNzlmLTRmNTQtYTAzNS01ZWIwNDcwYWU5MDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTVUMTEwMTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDY2Y2MzZDFlNTFmZmU5Yzg0MmJkY2E4YTI5M2MwMzRkNGIzOTJiNjg2NGJkZTFlMmQ0YTI3ZmJlZmVlM2FjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZUHWHy0nOznQ7Q9X7PexeXTIgjkRJ9-JRRev60ox1dg)
> 
> 复现步骤 (1)win分辨率2560x1440 (2)dawn窗口 800_1000，关闭dawn (3)win分辨率改低，高度比上面的1000低，比如1024_768 (4)开启dawn

啊你是改分辨率了啊，这也不算是BUG，算是一个需要优化的点吧，等我看看优化一下。
