### ISSUE TITLE
[新功能]快捷方式拖拽添加

### ISSUE THREAD

**Issue by ManakaGekka** [fanchenio/DawnLauncher#39]
目前向分类添加快捷方式时需要手动将快捷方式移动至对应文件夹中，现有拖拽复制操作无法使用，能否拖拽添加时直接将快捷方式移动至分类相对应的文件夹中

**Comment by fanchenio** [comment]
没懂你的意思，移动到文件夹中？Dawn不会去弄实体文件，它只是一个管理路径的一个软件，不会操作任何实体文件。

**Comment by ManakaGekka** [comment]
好的，感谢
