### ISSUE TITLE
我用Vstart快20年了，今天终于改用DawnLauncher

### ISSUE THREAD

**Issue by chenxin0397** [fanchenio/DawnLauncher#4]
如题，我用Vstart快20年了，今天终于改用DawnLauncher，Vstart里面还有很多功能其实还没用会，估计也用不上了，只是有一个功能我希望DawnLauncher也能实现，在Vstart启动的同时能设制多个同时启动的程序，虽然DawnLauncher里有批量启动，但比起“同时启动”来，还是需要每次都点一下。希望作者考虑实现这个功能吧！

**Comment by fanchenio** [comment]
了解，后续会增加的。

**Comment by Walkline80** [comment]
看见@chenxin0397提到了VStart那我也提一个需求吧，就是窗口靠边自动隐藏后，能否在那条边凸出显示几个像素，用来提示用户窗口隐藏在哪里了？

**Comment by fanchenio** [comment]
> 看见@chenxin0397提到了VStart那我也提一个需求吧，就是窗口靠边自动隐藏后，能否在那条边凸出显示几个像素，用来提示用户窗口隐藏在哪里了？

目前在想方案。
