### ISSUE TITLE
使用dawnlauncher打开的程序，以子进程方式存在

### ISSUE THREAD

**Issue by onegitting** [fanchenio/DawnLauncher#40]
使用dawnlauncher打开的程序，以子进程方式存在
dawnlauncher：1.4.2
OS：Windows 11 专业版 23H2 22631.3593
![123](https://github.com/fanchenio/DawnLauncher/assets/132970523/febb64c9-513c-4d70-b618-feff055796a9)

**Comment by fanchenio** [comment]
这个无视就行，不影响系统正常运行，也不影响你打开应用的运行，win11你可以隐藏一下窗口再显示一下窗口，应该就会分离出来了。
