### ISSUE TITLE
跨设备同步问题

### ISSUE THREAD

**Issue by oit63** [fanchenio/DawnLauncher#42]
兄弟，考虑过跨设备同步吗？
目前没找到合适的办法来在不同设备间同步
因为我一般是三个电脑在不同时候使用，对同步需求很大
看我们这边有没有什么办法解决这个问题

每次导出导入配置这个显然不现实

**Comment by fanchenio** [comment]
有人通过OneDrive实现配置文件的同步，你可以上网搜搜，类似文件同步的应用，应该都可以实现。

**Comment by oit63** [comment]
我以前是用onedrive来同步配置的
但主要就是生成的data文件里面有各种缓存文件，如Code Cache，GPUCache
然后就会在某个时候出现打不开Dawnlauncher的情况

我设想的是如果配置能单独放在一个文件夹，没有缓存文件来干扰，这样同步或许会很好
而且如果dawnlauncher会隔一段时间来读取配置，如果发现新的配置，会自动载入
这样就能通过网盘实现跨设备自动同步了

**Comment by oit63** [comment]
或者我们弄个收费的云同步功能，或者搞个webdav同步功能也是很好的 @ : )

**Comment by oit63** [comment]
还有个思路，就是用freefilesync，定时双向同步配置文件，只选配置文件来同步，也能实现同步功能，只是比较麻烦了。

**Comment by fanchenio** [comment]
> 我以前是用onedrive来同步配置的 但主要就是生成的data文件里面有各种缓存文件，如Code Cache，GPUCache 然后就会在某个时候出现打不开Dawnlauncher的情况
> 
> 我设想的是如果配置能单独放在一个文件夹，没有缓存文件来干扰，这样同步或许会很好 而且如果dawnlauncher会隔一段时间来读取配置，如果发现新的配置，会自动载入 这样就能通过网盘实现跨设备自动同步了

我不知道OneDrive能否同步单个文件，你只需要同步Data.db文件就可以了。
