### ISSUE TITLE
批量删除和添加项目时候很卡

### ISSUE THREAD

**Issue by blblank** [fanchenio/DawnLauncher#44]
批量删除和添加项目时候很卡，能优化一下吗

其他功能都很棒...

**Comment by fanchenio** [comment]
一般是多少个项目删除和添加会卡顿呢？告诉我个数量，我试试。

**Comment by blblank** [comment]
https://github.com/user-attachments/assets/57b83c14-c3d3-428d-ab60-6a13668da5eb

**Comment by blblank** [comment]
版本	Windows 10 企业版
版本号	22H2
安装日期	‎2024/‎7/‎6
操作系统内部版本	19045.4529
体验	Windows Feature Experience Pack 1000.19058.1000.0

设备名称	DESKTOP-MAUFK38
处理器	Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz   2.60 GHz
机带 RAM	16.0 GB
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

用的是机械硬盘

**Comment by fanchenio** [comment]
收到。

**Comment by fanchenio** [comment]
批量删除已优化，关于批量添加项目这个目前没有办法优化，因为批量添加项目会同步获取文件图标，如果这步不单独开启新的进程获取，获取图标数量大就会导致卡顿，这是为了整体体验，慢一点总比卡一点要好。
