### ISSUE TITLE
开启永远置顶后，失去焦点隐藏窗口无效

### ISSUE THREAD

**Issue by blblank** [fanchenio/DawnLauncher#47]
### Dawn Launcher 显示后，点击其他窗口不隐藏，必须得点一下Dawn Launcher窗口 再点其他窗口才会隐藏

**Comment by fanchenio** [comment]
因为置顶的作用其实就是让他在什么情况下都在最上面并且不消失，所以和失去焦点隐藏逻辑冲突，后面我会优化。
