### ISSUE TITLE
Launcher的log和cache该如何管理？

### ISSUE THREAD

**Issue by 909101** [fanchenio/DawnLauncher#49]
你好！

我试图用这个launcher打包一些文件并分享，但是发现data文件夹内有大量的设置文件，请问这些文件有哪些是必要的？哪些是可删除的？我希望在分享的时候不泄露任何关于我的电脑的信息。
谢谢！

**Comment by fanchenio** [comment]
如果分享数据的情况下只分享data.db即可。
