### ISSUE TITLE
操作launcher时会出现鼠标严重卡顿的情况

### ISSUE THREAD

**Issue by 909101** [fanchenio/DawnLauncher#50]
感谢回复我刚刚的issue！

在我过去几个月使用这个launcher的时间内，我经常发现，在launcher中进行操作后（打开项目，修改设置等），鼠标会立刻严重卡顿大约1-2秒，然后恢复正常。虽然这不影响任何功能，但是使用体验不太好，请问这是什么原因导致的呢？是electron导致的吗？

我一直在win11 23h2的系统里使用软件。

**Comment by fanchenio** [comment]
原因有多种，具体的话，还得具体分析，比如你提供动态图，我观察一下。
