### ISSUE TITLE
可以添加屏幕边缘时自动隐藏的功能吗？

### ISSUE THREAD

**Issue by uiroot** [fanchenio/DawnLauncher#51]
![image](https://github.com/user-attachments/assets/e2872b88-b863-4c67-8a5c-012d5738f0d4)

https://github.com/user-attachments/assets/494c2ff9-d6a5-41f6-b08e-1cebb75baf13

可以不用按快捷键

**Comment by fanchenio** [comment]
没理解，这个功能不是有吗？

**Comment by uiroot** [comment]
> 没理解，这个功能不是有吗？

鼠标靠近屏幕边缘主页自动跳出这个功能

**Comment by fanchenio** [comment]
还是没理解，Dawn Launcher已经有这个功能了啊。
