### ISSUE TITLE
請問子分類是否還不支持修改名稱

### ISSUE THREAD

**Issue by eric2100** [fanchenio/DawnLauncher#6]
請問子分類是否還不支持修改名稱

**Comment by fanchenio** [comment]
![image](https://github.com/fanchenio/DawnLauncher/assets/88647148/5eb83395-f5f3-4acf-b2fb-9cb4187943c9)

点击图标展开子分类或者双击父级分类展开子级分类，然后右键子分类就可以修改了。

**Comment by eric2100** [comment]
明白，謝謝，剛剛在未展開的地方，一直按右鍵找不到編修的功能，原來要展開。
