### ISSUE TITLE
多屏时"双击任务栏显示/隐藏"失效

### ISSUE THREAD

**Issue by Arthur2012** [fanchenio/DawnLauncher#8]
DawnLauncher省去了每次装机后重新设置开始菜单的烦恼，非常好用的软件，谢谢大佬！
这里提个小问题，就是多屏环境下，设置了"双击任务栏显示/隐藏"，在**跨屏**时会失效。只有在DawnLauncher显示所在的同一块屏幕的任务栏上双击才能生效。请大佬看看，谢谢！

**Comment by fanchenio** [comment]
是的，逻辑就是这样，如果你想在你所在屏幕显示，建议开启跟随鼠标显示。
